services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  textbelt:
    build: .
    container_name: textbelt
    ports:
      - "9099:9090"
    env_file: .env
